name: Deploy npm package
on:
    push:
      branches: quasar
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            ref: quasar
        - name: Setup Node.js environment
          uses: actions/setup-node@v4
        - uses: actions/setup-node@v4
        - run: npm install
        - name: build
          run: npm run build
        - uses: JS-DevTools/npm-publish@v3
          with:
            token: ${{ secrets.NPM_TOKEN }}